//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItiDays.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.StudentCourseDegrees = new HashSet<StudentCourseDegree>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Degree { get; set; }
        public Nullable<int> MinDegree { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCourseDegree> StudentCourseDegrees { get; set; }
    }
}
